### ISSUE TITLE
make antonym/synonym/rhyme words container scrollable

### ISSUE THREAD

**Issue by lesley-byte** [cmcclay77/super-team-project#40]

**Comment by lesley-byte** [comment]
:fire: I figured out scroll bars!!!:fire:
you add the class scroll to whatever you want and then in the css just put a bit that says something like
.scroll {
  overflow-y: scroll;
  height: 100vh;
}

:fire::fire::fire::fire::fire::fire::fire::fire::fire::fire::fire:

**Comment by hvansalisbury** [comment]
Scroll bars have been added to all four columns
